language: python
python:
  - "2.7"
install:
  - pip install -U platformio
cache:
  directories:
    - "~/.platformio"
    - "$TRAVIS_BUILD_DIR/.piolibdeps"
env:
  matrix:
    - BUILD_TARGET=livingroom
    - BUILD_TARGET=livingroom8266
    - BUILD_TARGET=custombmp180

script:
  - platformio run -e $BUILD_TARGET

matrix:
  fast_finish: true
  include:
  - env: BUILD_TARGET=livingroom
  - env: BUILD_TARGET=livingroom8266
  - env: BUILD_TARGET=custombmp180
  - env: BUILD_TARGET=dht-dallas-sensors
    if: branch = dev AND type = push
  - env: BUILD_TARGET=switch-binarysensor
    if: branch = dev AND type = push
  - env: BUILD_TARGET=fan-example
    if: branch = dev AND type = push
  - env: BUILD_TARGET=lights
    if: branch = dev AND type = push
  - env: BUILD_TARGET=i2c-sensors
    if: branch = dev AND type = push
  - env: BUILD_TARGET=pcf8574
    if: branch = dev AND type = push
  - env: BUILD_TARGET=fastled
    if: branch = dev AND type = push
  - env: BUILD_TARGET=sonoff-b1
    if: branch = dev AND type = push
