language: python
python:
  - "2.7"
install:
  - pip install -U platformio
cache:
  directories:
    - "~/.platformio"

matrix:
  fast_finish: true
  include:
  - env: BUILD_TARGET=livingroom
    script: &run_script
      - python travis/travis.py
      - platformio run -e $BUILD_TARGET
  - env: BUILD_TARGET=livingroom8266
    script: *run_script
  - env: BUILD_TARGET=custombmp180
    script: *run_script
  - env: BUILD_TARGET=fastled
    script: *run_script
    if: branch = dev AND type = push
  - dist: trusty
    sudo: require
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-7
        packages:
          - cmake
          - clang-tidy-7.0
          - clang-format-7.0
    before_script:
      - pio init --ide clion
      - patch -p0 < travis/neopixelbus.patch
      - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
    script:
      - python travis/run-clang-tidy.py
      - python travis/run-clang-format.py -i
