esphomeyaml:
  name: test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'abc'
  password: '1234567890'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '1234567890'

ota:
  password: '1234567890'

switch:
  - platform: gpio
    pin: 5
    name: red_light
    id: red_light

  - platform: gpio
    pin: 4
    name: green_light
    id: green_light

sensor:
  platform: adc
  name: weight
  pin: A0
  on_value_range:
    - above: 70
      then:
        - switch.turn_on: red_light
        - switch.turn_off: green_light
        
    - below: 60
      then:
        - switch.turn_on: red_light
        - switch.turn_off: green_light

